### PR TITLE
used 3rd party deno module for detecting content type

### PR DESCRIPTION
**Pull request by cstapetrei**
I think this is a cleaner solution than bringing in mime.js and all that :)

### CODE REVIEW

**Comment by lindsaykwardell** [comment]
Looks good to me, I wasn't aware of a Deno package yet. Thank you!

**Comment by lindsaykwardell** [comment]
FYI, I brought it into dev instead of master for now for testing, but it all looks good. Just want to do some more testing on the Socket class I added before bringing it into master and updating the release.

**Comment by cstapetrei** [comment]
Sure...no problem. Do you have any further plans for your wrapper ? Any quick ideas for features ? Maybe i can also give a hand :)

My 2c would be to extend the routing capabilities to regex and support query vars.

**Comment by lindsaykwardell** [comment]
Yep, that was the next place I was thinking of, specifically path parameters (like /user/{userId}). Query variables would be awesome. Feel free to jump in there!

Beyond that, my next thought is some sort of built-in route protection, or potentially some sort of middleware solution like Express. I think it would be nice to have a hook like:

```javascript
const router = new Router("/api")

router.auth = (req) => {
  // Perform auth check (JWT check, etc)
  
  return true;
}
```

Potentially could be used as a middleware method instead:

```javascript
const router = new Router("/api");

router.use((req) => {
  // Perform middleware Falsey return or calling req.response ends call.
})
```

**Comment by cstapetrei** [comment]
Re the router...path params were in my head too :)

With middlewares...i was thinking about smth along the lines of express too

`
app.use('/prefix', [middleware1, middleware2], routes);
`

though this format might need a bit of refactoring to the router

**Comment by lindsaykwardell** [comment]
That could work. I think I was taking the direction that all configuration of the router should take place on the Router class, and then the Server just consumes it from there. That way each route could be its own file, and you'd just have one file that imports them all and applies them. Although I don't see a reason it couldn't work both ways, as long as `Endpoint` now includes the middleware to apply to any given router.

Doing it both ways, the `app.use()` call could just allow for extra middleware to be applied to the `Endpoint` object.

Also, we'll probably need to change the function call for a route to return either void or boolean, so that the developer can pass either `true` or `false` to return in the middle of the middleware.

```javascript
const router = new Router("/api");

router.use(someMiddleware);

const app = new Server();

app.use(router.routes, someMiddleware2, someMiddleware3);
```

Server.ts
```javascript
public use(endpoint: Endpoint, ...middleware: Array<(req: ServerRequest) => boolean | void>): void {
   // Add middleware to endpoint before saving to object
}
```

**Comment by lindsaykwardell** [comment]
I'm going to break out some of what we've been talking about into issues so there's better tracking/conversation around it.

**Pull request merged**
